### ISSUE TITLE
As a user, I would like to be able to see the list of todos today when information is inputed. 

### ISSUE THREAD

**Issue by WILACHAT** [WILACHAT/ravi#2]
# USER SCENARIO
1. See lists of todos today for different rong when information is inputed in rong.html. 

#EXPECTED BEHAVIOR OF PROGRAM
1. Show the date and day of today.
2. Show all lists for todos today.
3. Show different color for each todos today rong. 
4. Still shows all the main button that can be redirect to other pages.

#TODO 
- [x] 1. Code the html logic that will display all the results.
- [x] 2. Use python to connect sql with html and code information that is not store in sql if any. 
- [x] 3. Query information from sql.
