### ISSUE TITLE
As a user, I would like to easily understand the concept of rong.html page. 

### ISSUE THREAD

**Issue by WILACHAT** [WILACHAT/ravi#4]
# USER SCENARIO
1. User is opening rong.html for the first time. 
2. User is opening rong.html when the user already created rong. 
3. User is adding new rong. 
4. User is filling in information for rong they are creating. 

# EXPECTED BEHAVIOR OF PROGRAM
1. Shows a beautiful and easy to understand design rong page. (first time opening or after inputed)
(the page will still need to show logo today rong and management button)
2. When users click the add new button a rongfilling.html page pops up. 
3. User will input all the information needed for example:
-rong number
-maybe rong name if want
-session might be automatically created
-date will be automatically created
4. A new rong should pop up in rong.html when new rong is created. 
5. Info that is inputed into rong will have to be inserted or updated to the rong database table

#TODO 
- [ ] 1. Create a html button for add new
- [ ] 2. Maybe create a html search form 
- [ ] 3. Create a new button every time rong is created that when click will lead to 4selection.html
- [ ] 4 Create a html form/post/submit when add new is clicked.
- [ ] 5. Code so that info in submit form will be insert or update to database.
- [ ] 6. CSS
