### ISSUE TITLE
As a user, I would like to easily understand how to fill in information to create a table for each session. 

### ISSUE THREAD

**Issue by WILACHAT** [WILACHAT/ravi#8]
# USER SCENARIO
1. Clicked into either change or new button in 4selection.html. (assuming that all the conditions are met)
2. Fill in the form that is required in the new/change.html page. 

#EXPECTED BEHAVIOR OF THE PROGRAM
1. Show a beautiful and self explanatory page of html forms and submit button. 
2. Every option to fill in will be in the same page so that the user will only have to scroll down. 
(maybe create a breadcrumb option so that user can navigate easier through options)
3. Have almost every form including:
-seed species (drop down from management)
-amount for ลงท่อ 
- start date (maybe automatically generated)
- how many days until ลงท่อ from start date (a1:b1 starts) (note 1) (note 2)
- how many days until ผสม from ลงท่อ (a2:b2 starts) (note 3) (note 4)
- how many days until ตัด from ผสม  (k starts accoring to user) (note 5)
- choose medicines from management (column of table will increase depending on amount of medicines chosen)
- how many everyday each medicine will be put from ลงท่อ then ผสม then ตัด
- how many everyday pui tarng bai ratio will be from ลงท่อ then ผสม then ตัด (one column select different ration each)
- how many day will this amount of ec goes for 

#TODO 
1. Create a html form/post/submit for:
- [ ] 1. seed species
- [ ] 2. amount that is originally planned 
- [ ] 3. start date
- [ ] 4. days until ลงท่อ
- [ ] 5. days until ผสม
- [ ] 6. days until ตัด 
- [ ] 7. choosing medicines
- [ ] 8. how many everyday for medicines
- [ ] 9. how many everyday for pui tarng bai
- [ ] 10. how many day will this amount of ec goes for 
- [ ] 11. how many day k will goes for 
- [ ] 12. note 1 note 2 note 3 note 4 note 5 
2. Database for:
- [ ] 1. Code using python and html to insert or update information that is inputed into database
- [ ] 2. Code so that users will have to only fill in once and the rest will be default (users can come and change still)
3. Everything will have to be in one page 
- [ ] 1. Maybe create a breadcrumb or find a easier way to navigate
